using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace UIFrame.Editor
{
    static class UIScriptWriter
    {
        public static void WritePanelScript(string path, string namespaceName, string className)
        {
            var ns = string.IsNullOrWhiteSpace(namespaceName) ? "Game" : namespaceName.Trim();
            var sb = new StringBuilder();
            sb.AppendLine("using UIFrame;");
            sb.AppendLine();
            sb.Append("namespace ").Append(ns).AppendLine();
            sb.AppendLine("{");
            sb.Append("    public partial class ").Append(className).AppendLine(" : UIPanel<UINone>");
            sb.AppendLine("    {");
            sb.AppendLine("        protected override void OnCreate()");
            sb.AppendLine("        {");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        protected override void OnOpen(UINone args)");
            sb.AppendLine("        {");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            WriteUtf8(path, sb.ToString());
        }

        public static void WriteItemScript(string path, string namespaceName, string className)
        {
            var ns = string.IsNullOrWhiteSpace(namespaceName) ? "Game" : namespaceName.Trim();
            var sb = new StringBuilder();
            sb.AppendLine("using UIFrame;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine();
            sb.Append("namespace ").Append(ns).AppendLine();
            sb.AppendLine("{");
            sb.Append("    public partial class ").Append(className).AppendLine(" : UIItem");
            sb.AppendLine("    {");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            WriteUtf8(path, sb.ToString());
        }

        public static void WriteGenScript(UIPrefabBindState state)
        {
            var ns = string.IsNullOrWhiteSpace(state.NamespaceName) ? "Game" : state.NamespaceName.Trim();
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// UIFrame 生成，请勿手改。在 Inspector 绑定后点「写入脚本」。");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine();
            sb.Append("namespace ").Append(ns).AppendLine();
            sb.AppendLine("{");
            sb.Append("    public partial class ").Append(state.ClassName).AppendLine();
            sb.AppendLine("    {");
            if (state.Binds != null)
            {
                for (var i = 0; i < state.Binds.Count; i++)
                {
                    var bind = state.Binds[i];
                    var typeName = bind.IsGameObject ? "UnityEngine.GameObject" : bind.TypeName;
                    sb.Append("        [SerializeField] private ").Append(typeName).Append(' ')
                        .Append(bind.FieldName).AppendLine(";");
                }
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            WriteUtf8(state.GenPath, sb.ToString());
        }

        public static void EnsureFolder(string assetFolder)
        {
            if (AssetDatabase.IsValidFolder(assetFolder))
            {
                return;
            }

            var parts = assetFolder.Replace('\\', '/').Split('/');
            var current = parts[0];
            for (var i = 1; i < parts.Length; i++)
            {
                var next = current + "/" + parts[i];
                if (!AssetDatabase.IsValidFolder(next))
                {
                    AssetDatabase.CreateFolder(current, parts[i]);
                }

                current = next;
            }
        }

        static void WriteUtf8(string assetPath, string content)
        {
            var full = ToFullPath(assetPath);
            var dir = Path.GetDirectoryName(full);
            if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir))
            {
                Directory.CreateDirectory(dir);
            }

            File.WriteAllText(full, content, new UTF8Encoding(false));
        }

        public static string ToFullPath(string assetPath)
        {
            var project = Directory.GetParent(Application.dataPath)?.FullName ?? Application.dataPath;
            return Path.GetFullPath(Path.Combine(project, assetPath.Replace('/', Path.DirectorySeparatorChar)));
        }
    }
}
